-- Supabase table for civic decisions timeline
create table if not exists public.civic_decisions (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  date date not null,
  title text not null,
  description text not null,
  tags text[] not null default '{}',
  source_link text,
  created_at timestamptz not null default now()
);

create index if not exists civic_decisions_date_idx on public.civic_decisions (date desc);

alter table public.civic_decisions enable row level security;

-- Public read access for static site timeline rendering
create policy if not exists "civic_decisions_public_read"
  on public.civic_decisions
  for select
  to anon
  using (true);

-- Optional seed data (5 placeholder decisions)
insert into public.civic_decisions (slug, date, title, description, tags, source_link)
values
  (
    'downtown-ada-sidewalk-repair-package',
    '2024-04-23',
    'Council advanced a downtown ADA sidewalk repair package.',
    'Phase one prioritizes high-foot-traffic blocks near schools and senior housing to improve walkability and safety before winter weather.',
    array['Infrastructure', 'Accessibility'],
    'https://example.com/decision/ada-sidewalk-repair'
  ),
  (
    'mixed-use-zoning-amendment-public-hearing',
    '2024-04-17',
    'Mixed-use zoning amendment moved to public hearing.',
    'The draft sets height transitions, active street frontage, and design requirements near core corridors ahead of a formal public hearing.',
    array['Planning', 'Zoning'],
    'https://example.com/decision/mixed-use-zoning'
  ),
  (
    'trail-lighting-upgrade-northern-state-corridor',
    '2024-04-09',
    'City approved trail lighting upgrade near Northern State corridor.',
    'Installation is expected in late summer and is coordinated with utility scheduling to improve evening visibility for trail users.',
    array['Parks', 'Public Safety'],
    'https://example.com/decision/trail-lighting'
  ),
  (
    'main-street-crosswalk-timing-adjustment',
    '2024-04-03',
    'Main Street crosswalk timing adjustments approved for school commute hours.',
    'Signal timing changes add longer crossing windows during morning drop-off and afternoon pickup periods around school routes.',
    array['Transportation', 'Schools'],
    'https://example.com/decision/crosswalk-timing'
  ),
  (
    'library-meeting-room-reservation-pilot',
    '2024-03-27',
    'Library launched a pilot for online community meeting room reservations.',
    'Residents can reserve library meeting rooms online during a six-month pilot designed to simplify bookings and improve room usage visibility.',
    array['Library', 'Digital Services'],
    'https://example.com/decision/library-room-pilot'
  )
on conflict (slug) do update set
  date = excluded.date,
  title = excluded.title,
  description = excluded.description,
  tags = excluded.tags,
  source_link = excluded.source_link;
